/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, once) {
  var deprecatedMessageSuffix = "is deprecated in Drupal 9.3.0 and will be removed in Drupal 10.0.0. Use the core/once library instead. See https://www.drupal.org/node/3158256";
  var originalJQOnce = $.fn.once;
  var originalJQRemoveOnce = $.fn.removeOnce;

  $.fn.once = function jQueryOnce(id) {
    Drupal.deprecationError({
      message: "jQuery.once() ".concat(deprecatedMessageSuffix)
    });
    return originalJQOnce.apply(this, [id]);
  };

  $.fn.removeOnce = function jQueryRemoveOnce(id) {
    Drupal.deprecationError({
      message: "jQuery.removeOnce() ".concat(deprecatedMessageSuffix)
    });
    return originalJQRemoveOnce.apply(this, [id]);
  };

  var drupalOnce = once;

  function augmentedOnce(id, selector, context) {
    originalJQOnce.apply($(selector, context), [id]);
    return drupalOnce(id, selector, context);
  }

  function remove(id, selector, context) {
    originalJQRemoveOnce.apply($(selector, context), [id]);
    return drupalOnce.remove(id, selector, context);
  }

  window.once = Object.assign(augmentedOnce, drupalOnce, {
    remove: remove
  });
})(jQuery, once);;
var tarteaucitronCustomText = {
  "middleBarHead": "☝ 🍪",
  "adblock": "Bonjour! Ce site joue la transparence et vous donne le choix des services tiers à activer.",
  "adblock_call": "Merci de désactiver votre adblocker pour commencer la personnalisation.",
  "reload": "Recharger la page",

  "alertBigScroll": "En continuant de défiler,",
  "alertBigClick": "En poursuivant votre navigation,",
  "alertBig": "vous acceptez l'utilisation de services tiers pouvant installer des cookies",

  "alertBigPrivacy" : "<h1 class='tarteaucitron-title fr-h3'>À propos des cookies sur defense.gouv.fr</h1>" +
    "<p>Bienvenue ! Ce site utilise des cookies pour mesurer la fréquentation du site afin d’en améliorer le fonctionnement et l’administration et, avec votre accord, pour évaluer la performance des campagnes d’informations gouvernementales et améliorer votre expérience utilisateur,\n" +
    "ainsi que pour vous proposer des services interactifs fournis par nos partenaires.</p>",

  "alertSmall": "<b>Gestion des services</b>",
  "acceptAll": "Tout accepter",
  "personalize": "Personnaliser",
  "close": "Fermer",

  "privacyUrl": "Politique de confidentialité",

  "all": "Préférences pour tous les services",

  "info": "Protection de votre vie privée",
  "disclaimer": "En autorisant ces services tiers, vous acceptez le dépôt et la lecture de cookies et l'utilisation de technologies de suivi nécessaires à leur bon fonctionnement.",
  "allow": "Autoriser",
  "deny": "Interdire",
  "noCookie": "Ce service ne dépose aucun cookie.",
  "useCookie": "Ce service peut déposer",
  "useCookieCurrent": "Ce service a déposé",
  "useNoCookie": "Ce service n'a déposé aucun cookie.",
  "more": "En savoir plus",
  "source": "Voir le site officiel",
  "credit": "Gestion des cookies par tarteaucitron.js",
  "noServices": "Ce site n'utilise aucun cookie nécessitant votre consentement.",

  "toggleInfoBox": "Afficher/masquer les informations sur le stockage des cookies",
  "title": "Panneau de gestion des cookies",
  "cookieDetail": "Détail des cookies",
  "ourSite": "sur notre site",
  "newWindow": "(nouvelle fenêtre)",
  "allowAll": "Tout accepter",
  "denyAll": "Tout refuser",
  "allowAllButtonTitle" : "Accepter tout les cookies",
  "denyAllButtonTitle" : "Refuser tout les cookies",

  "fallback": "est désactivé.",

  "ads": {
    "title": "Régies publicitaires",
    "details": "Les régies publicitaires permettent de générer des revenus en commercialisant les espaces publicitaires du site."
  },
  "analytic": {
    "title": "Mesure d'audience",
    "details": "Les services de mesure d'audience permettent de générer des statistiques de fréquentation utiles à l'amélioration du site."
  },
  "social": {
    "title": "Réseaux sociaux",
    "details": "Les réseaux sociaux permettent d'améliorer la convivialité du site et aident à sa promotion via les partages."
  },
  "video": {
    "title": "Vidéos",
    "details": "Les services de partage de vidéo permettent d'enrichir le site de contenu multimédia et augmentent sa visibilité."
  },
  "comment": {
    "title": "Commentaires",
    "details": "Les gestionnaires de commentaires facilitent le dépôt de vos commentaires et luttent contre le spam."
  },
  "support": {
    "title": "Support",
    "details": "Les services de support vous permettent d'entrer en contact avec l'équipe du site et d'aider à son amélioration."
  },
  "api": {
    "title": "APIs",
    "details": "Les APIs permettent de charger des scripts : géolocalisation, moteurs de recherche, traductions, ..."
  },
  "other": {
    "title": "Autre",
    "details": "Services visant à afficher du contenu web."
  },

  "mandatoryTitle": "Cookies obligatoires",
  "mandatoryText": "Ce site utilise des cookies nécessaires à son bon fonctionnement qui ne peuvent pas être désactivés."
};
;
/**
 * @file
 * Open Theme behaviors.
 */

(function ($, Drupal, tarteaucitron) {

    'use strict';

    /**
     * Behavior description.
     */
    Drupal.behaviors.openTacJs = {
      attach: function (context, settings) {
        // Create new services.
        customAtInternet(settings.tagAtInternet);
        optOutAtInternet();
        customDsfrFacebook();
        customDsfrTwitter();
        customDsfrLinkedin();
        customYoutubeService();

        $("main", context).once('openTacJs').each(function () {
          addTagAtInternet(settings.tagAtInternet);
          let jobs = [
            'customAtInternet',
            'atinternethightrack',
            'customYoutubeService',
            'customDsfrFacebook',
            'customDsfrTwitter',
            'customDsfrLinkedin'
          ]

          //Init tacjs et parametre de base
          init();

          //Activation des services souhaités
          jobs.forEach(job => {
            (tarteaucitron.job = tarteaucitron.job || []).push(job);
          });
          tarteaucitron.userInterface.respondAll = respondAll;
          setButtonTitleAttributes();
        });
      }
    };

    // List of disabled social networks.
    let socialNetworkDisableList = [];

    const init = () => {
      tarteaucitron.init({
        "privacyUrl": "", /* Privacy policy url */
        "hashtag": "#preferences-cookies", /* Open the panel with this hashtag */
        "cookieName": "cookie-compliance", /* Cookie name */
        "orientation": "bottom", /* Banner position (top - bottom) */
        "bodyPosition": "top",
        "groupServices": false, /* Group services by category */
        "showAlertSmall": false, /* Show the small banner on bottom right */
        "cookieslist": true, /* Show the cookie list */
        "closePopup": false, /* Show a close X on the banner */
        "showIcon": false, /* Show cookie icon to manage cookies */
        //"iconSrc": "", /* Optionnal: URL or base64 encoded image */
        "iconPosition": "BottomRight", /* BottomRight, BottomLeft, TopRight and TopLeft */
        "adblocker": false, /* Show a Warning if an adblocker is detected */
        "DenyAllCta": true, /* Show the deny all button */
        "AcceptAllCta": true, /* Show the accept all button when highPrivacy on */
        "highPrivacy": true, /* HIGHLY RECOMMANDED Disable auto consent */
        "handleBrowserDNTRequest": false, /* If Do Not Track == 1, disallow all */
        "removeCredit": true, /* Remove credit link */
        "moreInfoLink": true, /* Show more info link */
        "useExternalCss": true, /* If false, the tarteaucitron.css file will be loaded */
        "useExternalJs": false, /* If false, the tarteaucitron.js file will be loaded */
        //"cookieDomain": ".my-multisite-domaine.fr", /* Shared cookie for multisite */
        "readmoreLink": "/donnees-personnelles-et-cookies", /* Change the default readmore link */
        "mandatory": false, /* Show a message about mandatory cookies */
      });
    };

    const addTagAtInternet = (atInternetTag) => {
      const isTACAllowed = tarteaucitron.cookie.read().includes('customAtInternet=true');
      const regexTag = new RegExp('^[0-9]{6}$');

      if (!regexTag.test(atInternetTag) || !isTACAllowed) {
        return;
      }

      tarteaucitron.user.atLibUrl = `//tag.aticdn.net/${atInternetTag}/smarttag.js`;
      tarteaucitron.user.atMore = function () {
        const tag = new ATInternet.Tracker.Tag();
        tag.events.send('page.display', {
          'page': window.location.href
        });

        tag.dispatch();
      };

      tarteaucitron.addScript(tarteaucitron.user.atLibUrl, '', () => {
        if (typeof tarteaucitron.user.atMore === 'function') {
          tarteaucitron.user.atMore();
        }
      });
    }

    // MINARMSITE-884 - custom service youtube to change iframe title. copy from public/tarteaucitron.service.js.
    const customYoutubeService = () => {
      // youtube
      tarteaucitron.services.customYoutubeService = {
        "key": "customYoutubeService",
        "type": "video",
        "name": "YouTube",
        "uri": "https://policies.google.com/privacy",
        "needConsent": true,
        "cookies": ['VISITOR_INFO1_LIVE', 'YSC', 'PREF', 'GEUP'],
        "js": function () {
          "use strict";
          tarteaucitron.fallback(['youtube_player'], function (x) {
            let frame_title = tarteaucitron.fixSelfXSS(tarteaucitron.getElemAttr(x, "title") || 'Vidéo sur Youtube'),
              video_id = tarteaucitron.getElemAttr(x, "videoID"),
              srcdoc = tarteaucitron.getElemAttr(x, "srcdoc"),
              loading = tarteaucitron.getElemAttr(x, "loading"),
              video_width = tarteaucitron.getElemAttr(x, "width"),
              frame_width = 'width=',
              video_height = tarteaucitron.getElemAttr(x, "height"),
              frame_height = 'height=',
              video_frame,
              allowfullscreen = tarteaucitron.getElemAttr(x, "allowfullscreen"),
              attrs = ["theme", "rel", "controls", "showinfo", "autoplay", "mute", "start", "loop"],
              params = attrs.filter(function (a) {

                return tarteaucitron.getElemAttr(x, a) !== null;
              }).map(function (a) {
                return a + "=" + tarteaucitron.getElemAttr(x, a);
              }).join("&");

            if (tarteaucitron.getElemAttr(x, "loop") == 1) {
              params = params + "&playlist=" + video_id;
            }

            if (video_id === undefined) {
              return "";
            }
            if (video_width !== undefined) {
              frame_width += '"' + video_width + '" ';
            } else {
              frame_width += '"" ';
            }
            if (video_height !== undefined) {
              frame_height += '"' + video_height + '" ';
            } else {
              frame_height += '"" ';
            }

            if (srcdoc !== undefined && srcdoc !== null && srcdoc !== "") {
              srcdoc = 'srcdoc="' + srcdoc + '" ';
            } else {
              srcdoc = '';
            }

            if (loading !== undefined && loading !== null && loading !== "") {
              loading = 'loading ';
            } else {
              loading = '';
            }

            video_frame = '<iframe title="' + frame_title + '" type="text/html" ' + ' src="//www.youtube-nocookie.com/embed/' + video_id + '?' + params + '"' + (allowfullscreen == '0' ? '' : ' webkitallowfullscreen mozallowfullscreen allowfullscreen') + ' ' + srcdoc + ' ' + loading + ' loading="lazy"></iframe>';
            return video_frame;
          });
        },
        "fallback": function () {
          "use strict";
          const id = 'customYoutubeService';
          tarteaucitron.fallback(['youtube_player'], function (elem) {
            elem.style.width = elem.getAttribute('width') + 'px';
            elem.style.height = elem.getAttribute('height') + 'px';
            return tarteaucitron.engage(id);
          });
        }
      };

    }

    const customDsfrFacebook = () => {
      tarteaucitron.services.customDsfrFacebook = {
        "key": "customDsfrFacebook",
        "type": "social",
        "name": "Facebook",
        "needConsent": true,
        "cookies": [],
        "uri": "https://fr-fr.facebook.com/policies/cookies/",
        "js": function () {
          // Allowed.
          "use strict";
          shareToShow('facebook', 'https://www.facebook.com/sharer.php?u=');
        },
        "fallback": function () {
          // Unallowable.
          "use strict";
          shareToHide('facebook');
        }
      };
    }

    const customDsfrTwitter = () => {
      tarteaucitron.services.customDsfrTwitter = {
        "key": "customDsfrTwitter",
        "type": "social",
        "name": "Twitter",
        "uri": "https://support.twitter.com/articles/20170514",
        "needConsent": true,
        "cookies": [],
        "js": function () {
          // Allowed.
          "use strict";
          shareToShow('twitter', 'https://twitter.com/intent/tweet?url=');
        },
        "fallback": function () {
          // Unallowable.
          "use strict";
          shareToHide('twitter');
        }
      };
    }

    const customDsfrLinkedin = () => {
      tarteaucitron.services.customDsfrLinkedin = {
        "key": "customDsfrLinkedin",
        "type": "social",
        "name": "Linkedin",
        "uri": "https://www.linkedin.com/legal/cookie_policy",
        "needConsent": true,
        "cookies": [],
        "js": function () {
          // Allowed.
          "use strict";
          shareToShow('linkedin', 'https://www.linkedin.com/shareArticle?url=');
        },
        "fallback": function () {
          // Unallowable.
          "use strict";
          shareToHide('linkedin');
        }
      };
    }

    const customAtInternet = (tag) => {
      tarteaucitron.services.customAtInternet = {
        "key": "customAtInternet",
        "type": "analytic",
        "name": "AT Internet exemption CNIL",
        "readmoreLink": "/donnees-personnelles-et-cookies",
        "uri": "https://www.atinternet.com/rgpd-et-vie-privee/exemption-cnil-web-analytics/",
        "needConsent": false,
        "allowedByDefault": true,
        "safeanalytic": true,
        "cookies": ['atidvisitor', 'atreman', 'atredir', 'atsession', 'atuserid', 'atauthority'],
        "js": function () {
          "use strict";

          addTagAtInternet(tag);

          const tarteaucitronAllowed = document.querySelector('#customAtInternetAllowed');
          tarteaucitronAllowed.style.display = 'none';
          document.querySelector('#customAtInternetDenied').style.display = 'none';
          const isTACAllowed = tarteaucitron.cookie.read().includes('customAtInternet=true');

          const p = document.createElement('p');
          p.setAttribute('id', 'askState');
          p.innerHTML = 'Activé';
          tarteaucitronAllowed.insertAdjacentElement('beforebegin', p);

          if (isTACAllowed) {
            tarteaucitron.launch['atinternethightrack'] = true;
            tarteaucitron.userInterface.respond(document.querySelector('#atinternethightrackAllowed'), true);
          }

          tarteaucitron.reloadThePage = true;
        },
      }
    }

    const optOutAtInternet = () => {
      const text_fr = 'Vous pouvez désactiver la mesure d\'audience des données strictement nécessaires en cliquant sur le lien "en savoir plus"';
      const optOutButton = document.querySelector('[href="#opt-out-at-internet"]');

      setTimeout(function () {
        // Hide atinternethightrack (keep hightrack to be launch with custom).
        let atinternethightrackLine = document.querySelector('#atinternethightrackLine');
        if (atinternethightrackLine) {
          atinternethightrackLine.style.display = 'none';
        }

        // Text info for optout
        if (document.getElementById("atinternetcnilTextinfo") === null) {
          let textinfo = document.createElement("span");
          let parentDiv = document.getElementById("tacCLcustomAtInternet")?.parentNode;
          let sp2 = document.getElementById("tacCLcustomAtInternet");
          const currentStatusAT = document.querySelector('#tacCurrentStatuscustomAtInternet')
          const readmoreSeparator = document.querySelector('#customAtInternetLine .tarteaucitronReadmoreSeparator')

          if (currentStatusAT) {
            currentStatusAT.style.display = 'none';
          }

          if (readmoreSeparator) {
            readmoreSeparator.style.display = 'none';
          }

          textinfo.setAttribute('id', 'atinternetcnilTextinfo')
          textinfo.classList.add('fr-text--sm');
          textinfo.innerHTML = text_fr;
          textinfo.style.display = 'block';
          if (parentDiv && sp2) {
            parentDiv.insertBefore(textinfo, sp2);
          }
        }
      }, 500);

      // Prepare to desactivate CNIL.
      if (optOutButton) {
        optOutButton.addEventListener('click', event => {
          event.preventDefault();

          setTimeout(function () {
            tarteaucitron.launch['atinternethightrack'] = true;
            tarteaucitron.userInterface.respond(document.querySelector('#atinternethightrackAllowed'), false);
            tarteaucitron.launch['customAtInternet'] = true;
            tarteaucitron.userInterface.respond(document.querySelector('#customAtInternetAllowed'), false);
            location.reload();
          }, 500);
        });
      }
    }

    // Check if all social network are allowed and hide/show cookies accordingly.
    const checkAllAllowed = () => {
      const countDisable = document.querySelectorAll('.fr-share .fr-btns-group>li a[aria-disabled]').length;
      let shareElement = document.querySelector('.fr-share');
      if (!shareElement) {
        return;
      }
      if (countDisable < 1) {
        shareElement.classList.add('fr-share--all-allowed');
      } else {
        setCookieWording();
        shareElement.classList.remove('fr-share--all-allowed');
      }
    }

    // Disable social network sharing.
    const shareToHide = (socialName) => {
      socialNetworkDisableList.push(socialName);
      const elementToHide = document.querySelectorAll('.fr-share .fr-btn--' + socialName)[0];
      if (elementToHide) {
        const elementToHideTitle = elementToHide.getAttribute('title') + ' - désactivé';
        elementToHide.setAttribute('role', 'link');
        elementToHide.setAttribute('title', elementToHideTitle);
        elementToHide.removeAttribute('href');
        elementToHide.setAttribute('aria-disabled', 'true');
        elementToHide.removeEventListener('click', (event) => event.preventDefault());
      }

      checkAllAllowed();
    }

    // allowe social network sharing.
    const shareToShow = (socialName, shareLink) => {
      socialNetworkDisableList = socialNetworkDisableList.filter(item => item !== socialName);

      const elementToShow = document.querySelectorAll('.fr-share .fr-btn--' + socialName)[0];
      const href = shareLink + window.location.href;

      if (elementToShow) {
        elementToShow.setAttribute('href', href);
        elementToShow.removeAttribute('aria-disabled');
        elementToShow.removeAttribute('role');
        elementToShow.addEventListener('click', (event) => {
          event.preventDefault();
          window.open(elementToShow.href, `Partager sur ${toCapitalize(socialName)}`, 'toolbar=no,location=yes,status=no,menubar=no,scrollbars=yes,resizable=yes,width=600,height=450');
        });
      }
      checkAllAllowed();
    }

    // Set title attributes on button deny and accept all.
    const setButtonTitleAttributes = () => {
      setTimeout(function () {
        document.querySelector('#tarteaucitronPersonalize2').setAttribute("title", tarteaucitron.lang.allowAllButtonTitle);
        document.querySelector('#tarteaucitronAllDenied2').setAttribute("title", tarteaucitron.lang.denyAllButtonTitle);
      }, 500);
    }

    // Change cookies wording according to the list of disabled items.
    const setCookieWording = () => {
      let cookieWording = document.querySelector('span.cookie-social-wording');
      let text = '';
      socialNetworkDisableList.forEach((social, index, array) => {
        const formatedSocial = toCapitalize(social);

        if (array.length === index + 1) {
          const conditionalAnd = array.length > 1 ? ' et ' : '';
          text = `${text} ${conditionalAnd} ${formatedSocial}.`;
          return;
        }

        if (array.length > 1) {
          const comma = index > 0 ? ', ' : '';
          text = `${text}${comma}${formatedSocial}`;
        }
      });
      cookieWording.innerHTML = text;

    }

    const toCapitalize = (string) => {
      return (string?.charAt(0).toUpperCase() + string?.slice(1)) ?? string;
    }

    // Use to tarteaucitron.js to keep customAtInternet activate.
    const respondAll = (status, type, allowSafeAnalytics) => {
      "use strict";
      var s = tarteaucitron.services,
        service,
        key,
        index = 0;

      const blacklistServices = ['customAtInternet'];

      for (index = 0; index < tarteaucitron.job.length; index += 1) {

        if (typeof type !== 'undefined' && type !== '' && s[tarteaucitron.job[index]].type !== type) {
          continue;
        }

        if (allowSafeAnalytics && typeof s[tarteaucitron.job[index]].safeanalytic !== "undefined" && s[tarteaucitron.job[index]].safeanalytic === true) {
          continue;
        }

        service = s[tarteaucitron.job[index]];
        if (!service) {
          continue;
        }
        key = service.key;

        if (tarteaucitron.state[key] !== status) {
          if (status === false && tarteaucitron.launch[key] === true) {
            tarteaucitron.reloadThePage = true;
            if (tarteaucitron.checkIfExist('tarteaucitronClosePanel')) {
              var ariaCloseValue = document.getElementById('tarteaucitronClosePanel').textContent.trim() + ' (' + tarteaucitron.lang.reload + ')';
              document.getElementById('tarteaucitronClosePanel').setAttribute("aria-label", ariaCloseValue);
              document.getElementById('tarteaucitronClosePanel').setAttribute("title", ariaCloseValue);
            }
          }
          if (tarteaucitron.launch[key] !== true && status === true) {
            tarteaucitron.pro('!' + key + '=engage');

            tarteaucitron.launch[key] = true;
            if (typeof tarteaucitronMagic === 'undefined' || tarteaucitronMagic.indexOf("_" + key + "_") < 0) {
              tarteaucitron.services[key].js();
            }
            tarteaucitron.sendEvent(key + '_loaded');
          }
          var itemStatusElem = document.getElementById('tacCurrentStatus' + key);

          if (status) {
            itemStatusElem.innerHTML = tarteaucitron.lang.allowed;
          } else {

            if (blacklistServices.includes(key)) {
              continue;
            }

            itemStatusElem.innerHTML = tarteaucitron.lang.disallowed;
          }
          tarteaucitron.state[key] = status;
          tarteaucitron.cookie.create(key, status);
          tarteaucitron.userInterface.color(key, status);
        }
      }
    }

  }
  (jQuery, Drupal, tarteaucitron)
);
;
